### ISSUE TITLE
Feature request: Custom colouring by SubBlock and Genotype for layout plots in plot.TD

### ISSUE THREAD

**Issue by josephoddy** [Biometris/statgenSTA#1]
Hi, I've been using the package to plot layouts of field trials I am currently managing and have found it very useful for visualisation. I was wondering if it would be possible to add something which allows users to specify custom colours for the "layout" plot types within plot.TD. At the moment it defaults to the default ggplot2 colour palette which is difficult to distinguish when highlighting many genotypes and when there are many different sub-blocks in the field design.
Thanks.

**Comment by BartJanvanRossum** [comment]
I didn't notice your issue earlier. But your suggestions sound good. I'm planning on releasing a new version of the package soon. I will see if I can include this then

**Comment by BartJanvanRossum** [comment]
These suggestions are included in version 1.0.7 that was just published on CRAN

**Comment by josephoddy** [comment]
Works great, thanks!
