### ISSUE TITLE
Bug in plot.STA()

### ISSUE THREAD

**Issue by marktgee** [Biometris/statgenSTA#2]
The plot.STA() function in the statgenSTA package has a bug when generating the base plots.

Data is extracted from the STA object and stored in dataframes "fitted", "pred", and "response". These three dataframes are merged into a "plotDat" dataframe based on columns identified in the "mergeCols" variable. 

As currently written, the "mergeCols" variable includes genotype when generating base plots but does not include colCoord and rowCoord.

In datasets where each genotype has multiple datapoints due to a replicated experimental design, the genotype information alone is not enough for the merge() function to correctly identify which values of the "fitted" and "response" dataframes should be paired together. The merge function handles the duplicate genotypes observations by including every possible combination of the response and fitted data with the same genotype. This leads to a plotDat dataframe with many more rows than the original dataset which is composed of fictitious data that results from the pairing of data from different replications. This incorrect data leads to plots that do not represent the model.

---------------------------------------
Solution

When the colCoord and rowCoord are also included in the "mergeCols" variable, each observation from the "fitted" and "response" dataset are uniquely identified and the merge function can correctly pair the dataframes. The resulting plotDat dataframe is the same size as the original datasets and the subsequent plots match the results obtained when the residual data is manually extracted from the model.

In the plot.STA() function, I modified this segment of code

 if (plotType == "spatial") {
       mergeCols <- c("colCoord", "rowCoord")
     }

to this

mergeCols <- c("colCoord", "rowCoord")

so that the merge function has sufficient information to uniquely merge datapoints even when plotting the base plots.

**Comment by BartJanvanRossum** [comment]
Thanks for finding this and for your proposed solution. It is fixed in the develop branch of the package and will be included in the next release

**Comment by BartJanvanRossum** [comment]
Closing this as version 1.0.9 was published on CRAN containing this fix
