### ISSUE TITLE
Passing on arguments to asreml

### ISSUE THREAD

**Issue by GregorDall** [Biometris/statgenSTA#6]
Hi, 

I am now working with asreml backend. I am getting errors from asreml, which might be dealt with by passing on arguments to asreml. As far as I understood, fitTD only passes on certain arguments. Any chance you could open this up for other/any argument? 

Best, Gregor

Warning message:
Error in asreml for model AR1(x)id genotype random, trait yield14dtha in trial ...:
Error   : 1 singularities in the Average Information matrix.
          : To continue the analysis anyway, try running it again with the optional argument ai.sing = TRUE

**Comment by BartJanvanRossum** [comment]
Hi Gregor,

The easiest way to do this at the moment is by specifying the asreml options you want to set before calling the fitTD function. So in your case you could do something like this:

```r
asreml::asreml.options(ai.sing = TRUE)
fitTD()
```

Best, Bart-Jan

**Comment by GregorDall** [comment]
Thanks, this will be fully sufficient!
