### ISSUE TITLE
I got this error message from ggplot2

### ISSUE THREAD

**Issue by envanloo** [Biometris/statgenSTA#7]
the dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
i Please use `after_stat(count)` instead.
i The deprecated feature was likely used in the statgenSTA package.
  Please report the issue at <https://github.com/Biometris/statgenSTA/issues>.
This warning is displayed once every 8 hours.

I am using stagenSTA 1.0.9

Is there an advice how to avoid this becoming a problem?

**Comment by BartJanvanRossum** [comment]
This issue was fixed in statgenSTA version 1.0.10.    
The current CRAN version is 1.0.12, so just updating to the latest version should solve the problem.

**Comment by envanloo** [comment]
thnx!

Dr. E.N. van Loo (Robert)
Wageningen UR
Plant Breeding
Droevendaalsesteeg 1
6708 PB Wageningen
The Netherlands
+31653726769

On 5 Feb 2024, at 08:43, Bart-Jan van Rossum ***@***.***> wrote:

﻿

This issue was fixed in statgenSTA version 1.0.10.
The current CRAN version is 1.0.12, so just updating to the latest version should solve the problem.
